# numpy


- 행렬 / 선형대수 / 통계 패키지

- 머신러닝의 이론적 백그라운드는 선형대수와 통계로 이루어져 있다

- 사이킷런 같은 머신러닝 패키지가 넘파이 기반으로 되어 있다


    * 머신러닝 알고리즘이나 사이파이와 같은 과학, 통계 지원용 패키지를 직접 만드는 개발이 아니라면
    넘파이를 상세하기 알 필요는 없다지만, 넘파이를 이해하는 것이 파이썬 기반의 데이타분석과 머신러닝에 중요하다
    
    * 넘파이가 데이타 핸들링에 효율적으로 쉽고 편하고 할 수 없다.
      그러나 데이타 핸들링에 주로 사용하는 판다스도 많은 부분이 넘파이를 기반으로 만들어져 있다.
    
    * ndarray 
        - 넘파이 기반 데이타 타입
        - np.array()       

In [9]:
import numpy as np

list_1 = [1,2,3]
list_2 = [9,8,7]

arr = np.array([list_1, list_2])
print(arr)
print(type(arr))
print(arr.shape)

[[1 2 3]
 [9 8 7]]
<class 'numpy.ndarray'>
(2, 3)


In [11]:
# 두 번째 행에서 두번째 열의 요소 값을 100 변경
arr[1][1]=100
print(arr[1][1])

100


In [14]:
a = np.array([1,2,3])
b = np.array([[1,2,3]])

print(a.shape)
print(b.shape)

print(a.ndim,'차원')
print(b.ndim,'차원')

(3,)
(1, 3)
1 차원
2 차원


### 자료형

+ 넘파이의 배열 안에는 동일한 타입의 데이타만 저장 (****)
+ 이 점 때문에 파이썬보다 속도가 빠르게 처리

In [22]:
a = np.array([1,2,3.0,['hi']])

print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
object


In [20]:
a

array(['1', '2', '3.0', 'hi'], dtype='<U32')

In [23]:
b= np.array([ 100, 3.6, 'Hello'])
print(type(b))
print(b.dtype)

<class 'numpy.ndarray'>
<U32


In [24]:
b

array(['100', '3.6', 'Hello'], dtype='<U32')

In [1]:
  # [결과] <U11   : Unicode 문자열 

### nparray를 편리하게 생성

* arange() : 범위를 이용한 배열 만들기
* zeros() : 0으로 채우는 배열 만들기
* ones() : 1로 채우는 배열 만들기

In [25]:
z = np.zeros((5,5), dtype='int32')
print(z.dtype)
z

int32


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
# 1로 채워진 3행 4열 정수 배열을 만들기
z = np.ones((3,4), dtype='int32')
z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### ndarray의 차원과 크기를 변경 : reshape()

In [30]:
arr = np.arange(20)
print(arr.shape)

arr

(20,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
arr2 = arr.reshape(4,5)
print(arr2.shape)
arr2

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
arr2 = arr.reshape(-1,4)
print(arr2.shape)
arr2

(5, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### 인덱싱: 특정 데이타 추출

In [39]:
#------------------------------------------ (1) 단일값 출력
import numpy as np
arr = np.arange(1, 11)
print(arr)

## 세번째 요소 추출 
arr[2]

## 뒤에서 세번째 요소 추출 
arr[-3]

[ 1  2  3  4  5  6  7  8  9 10]


8

In [45]:
## 1부터 9까지 nparray를 만들고 3행 3열 2차원 구조로 변경한후
## 두번째 행의 세번째 열의 값 추출
nparray = np.arange(1,10)
nparray = nparray.reshape(3,3)
nparray[1][2]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
#------------------------------------------ (2) 슬라이싱 (:)
arr = np.arange(1, 10)

# 인덱스 2번째부터 4번째까지
arr[1:4]
# 인덱스 2번째부터 끝까지
arr[1:]
# 처음부터 인덱스 4번째까지
arr[:4]


array([1, 2, 3, 4])

In [83]:
## 2차원 배열에서 생성
"""
    1 2 3
    4 5 6
    7 8 9
"""
arr = np.arange(1,10)
arr = arr.reshape(3,3)
## 배열에서 1, 2, 4, 5 추출
arr[:2,:2]

## 배열에서 4, 5, 6, 7, 8, 9 추출
arr[-2:]

## 배열에서 2, 3, 5, 6 추출
arr[:2,-2:]

## 배열에서 1, 4 추출
arr[:2,0]

## 배열에서 전체 요소 추출
arr


## 배열에서 3, 6 추출
arr[:2,2]

# 지금은 너무 간단하다고 여기지만 추후에 데이타에서 많이 헷갈려서 여기서 시간 소요를 많이 한다


array([3, 6])

In [84]:
#------------------------------------------ (3) 블린인덱싱
# 조건 필터링과 검색을 같이 하기에 자주 사용

# 5보다 큰 요소들 추출
print(ndarr[ ndarr > 5 ])

# 8값 요소를 88로 변경
ndarr[ndarr == 8] = 88
print(ndarr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
