## 파이썬 기초 이해

In [1]:
print(int(True)) #1
print(int(False)) #0

1
0


In [2]:
print?

In [4]:
print([1,2,3]*2)
print([1,2,3]*0)

[1, 2, 3, 1, 2, 3]
[]


## 넘파이 기초 이해

In [5]:
import numpy as np

print(np.array([1,2,3])*2) 
print(np.array([1,2,3])*0)

[2 4 6]
[0 0 0]


In [8]:
print(np.array([[1,2],[1,3],[1,4]]) * np.array([1,10]))

[[ 1 20]
 [ 1 30]
 [ 1 40]]
